In [1]:
import sqlalchemy
import pandas as pd

engine = sqlalchemy.create_engine("mysql+mysqlconnector://root:secret2@0.0.0.0:3307/edb")

In [3]:
pd.read_sql("SHOW TABLES;", engine)

Empty DataFrame
Columns: [Tables_in_edb]
Index: []

In [4]:
users = [
    {
        'username':'dusty',
        'password': 'secret1',
        'p_hash': hash('secret1')
    },
    {
        'username':'dan',
        'password': 'secret2',
        'p_hash': hash('secret2')
    },
    {
        'username':'kirk',
        'password': 'secret3',
        'p_hash': hash('secret3')
    }
]

users = pd.DataFrame(users)

In [5]:
users.to_sql("users", con=engine, if_exists='replace', index=False)

3

In [6]:
pd.read_sql("SHOW TABLES;", engine)

  Tables_in_edb
0         users

In [8]:
user = 'dusty'
password = 'secret1'

pword_match = pd.read_sql(f"SELECT p_hash FROM users WHERE username='{user}'", engine).values.ravel()[0]==hash(password)

print(pword_match)

True

In [9]:
import requests
import json

test = {
    'username' : 'dusty',
    'password' : 'secret1',
    'action' : 'query',
    'query' : 'SELECT * FROM users',
}

resp = requests.post("http://127.0.0.1:8000/query/", json=test)

In [10]:
json.loads(resp.text)

{'authentication': True,
 'value': '{"username":{"0":"dan","1":"kirk","2":"dusty"},"password":{"0":"secret2","1":"secret3","2":"secret1"},"p_hash":{"0":-2566989531704977055,"1":-371198818440000599,"2":-3642227721646055876}}'}

In [11]:
query_results = pd.DataFrame(json.loads(json.loads(resp.text)['value']))

In [12]:
query_results

  username password               p_hash
0      dan  secret2 -2566989531704977055
1     kirk  secret3  -371198818440000599
2    dusty  secret1 -3642227721646055876

True